#!/usr/bin/env node
// Bundles the whole game — three.js, every module, the stylesheet — into one
// self-contained HTML file you can open straight from disk (no server needed).
//
//   node build.mjs        ->  fortnite.html
//
// The modules are wrapped one per IIFE in dependency order and their
// import/export statements rewritten, so nothing relies on the network.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(ROOT, p), 'utf8');

// Dependency order: every module only imports ones already defined above it.
const MODULES = [
  'util', 'models', 'physics', 'character', 'props', 'world', 'loot',
  'effects', 'building', 'storm', 'map', 'bus', 'poi_summering', 'poi_snowy',
  'poi_pumped', 'actor', 'ai', 'player', 'ui', 'game', 'lobby', 'main',
];

/** Rewrite one ES module into an IIFE body plus the list of names it exports. */
function transform(src) {
  const exported = [];
  const lines = src.split('\n');
  const out = [];

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];

    // import * as THREE from 'three';
    if (/^import \* as THREE from ['"]three['"];/.test(line)) {
      out.push('const THREE = __THREE;');
      continue;
    }
    // import { a, b } from './x.js';   (may wrap over several lines)
    const namedStart = line.match(/^import\s*\{/);
    if (namedStart) {
      let block = line;
      while (!/from\s*['"][^'"]+['"];?\s*$/.test(block) && i + 1 < lines.length) block += ' ' + lines[++i];
      const m = block.match(/^import\s*\{([\s\S]*?)\}\s*from\s*['"]\.\/([^'"]+)\.js['"];?/);
      if (!m) throw new Error('unhandled import: ' + block);
      const names = m[1].split(',').map(s => s.trim()).filter(Boolean)
        .map(s => s.includes(' as ') ? s.replace(/\s+as\s+/, ': ') : s);
      out.push(`const { ${names.join(', ')} } = __m['${m[2]}'];`);
      continue;
    }
    if (/^import /.test(line)) throw new Error('unhandled import: ' + line);

    // export function / class / const / let
    let m = line.match(/^export\s+(async\s+)?function\s+([A-Za-z_$][\w$]*)/);
    if (m) { exported.push(m[2]); out.push(line.replace(/^export\s+/, '')); continue; }
    m = line.match(/^export\s+class\s+([A-Za-z_$][\w$]*)/);
    if (m) { exported.push(m[1]); out.push(line.replace(/^export\s+/, '')); continue; }
    m = line.match(/^export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/);
    if (m) { exported.push(m[2]); out.push(line.replace(/^export\s+/, '')); continue; }
    if (/^export\s/.test(line)) throw new Error('unhandled export: ' + line);

    out.push(line);
  }
  return { body: out.join('\n'), exported };
}

// ---------------------------------------------------------------------------
const three = read('vendor/three.module.js');
const exportStmt = three.match(/^export \{([\s\S]*?)\};?\s*$/m);
if (!exportStmt) throw new Error('could not find the three.js export list');
const threeNames = exportStmt[1].split(',').map(s => s.trim()).filter(Boolean);

let bundle = `${three}\nconst __THREE = { ${threeNames.join(', ')} };\nconst __m = {};\n`;
for (const name of MODULES) {
  const { body, exported } = transform(read(`src/${name}.js`));
  bundle += `\n// ===================== src/${name}.js =====================\n`;
  bundle += `__m['${name}'] = (function () {\n${body}\nreturn { ${exported.join(', ')} };\n})();\n`;
}

const css = read('style.css');
const html = read('index.html');
const title = (html.match(/<title>([\s\S]*?)<\/title>/) || [, 'Fortnite'])[1];
// the favicon href is an inline SVG data URI, so match the whole line rather
// than stopping at the first '>' inside it
const favicon = (html.match(/^<link rel="icon".*$/m) || [''])[0];

const outHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="theme-color" content="#0d1220" />
<title>${title}</title>
${favicon}
<!--
  Single-file build - three.js, all game modules and the stylesheet inlined.
  Generated by build.mjs; edit the files in src/ and re-run it, not this file.
-->
<style>
${css}
</style>
</head>
<body>
  <canvas id="game-canvas"></canvas>
  <div id="ui-root"></div>
  <div id="overlay" class="overlay" style="display:none"></div>
  <noscript>This game needs JavaScript and WebGL.</noscript>
<script type="module">
${bundle}
</script>
</body>
</html>
`;

writeFileSync(join(ROOT, 'fortnite.html'), outHtml);
console.log(`fortnite.html  ${(outHtml.length / 1048576).toFixed(2)} MB  (${MODULES.length} modules, three.js r${(three.match(/REVISION = '(\d+)'/) || [, '?'])[1]})`);
